### ISSUE TITLE
Make "ani" command more specific in profile

### ISSUE THREAD

**Issue by 4cecoder** [4cecoder/config#2]
Add specifics to ani-cli command alias ani="ani-cli quality whatever"

**Comment by 4cecoder** [comment]
please add stuff to
https://github.com/4cecoder/config/blob/main/profile#L8

**Comment by justchokingaround** [comment]
`alias aniq="ani-cli -q` ?

**Comment by 4cecoder** [comment]
> `alias aniq="ani-cli -q` ?
ok

**Comment by justchokingaround** [comment]
added
